### PR TITLE
added scenario folder

### PR DESCRIPTION
**Pull request by kbleffert**

### CODE REVIEW

**Comment by jennyfothergill** [comment]
@kbleffert your title is added folder, but I don't see a folder in your PR. Is somethign missing?

**Comment by kbleffert** [comment]
Yes, I supposed so. How to I add a folder to a commit? It won't let me

**Comment by jennyfothergill** [comment]
there needs to be at least one file in the folder

**Review by jennyfothergill — CHANGES_REQUESTED** [review]
add at least one file to the folder so it will show up

**Pull request merged**
