### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ashtonenrriques**
Deleted contributors and consolidated into contributors.txt
updated and deleted repeated names/ emails
updated idaho_infections.csv up to 2020-040-13
moved idaho_infections.csv into own sub-directory to try to graph
trying to graph actual idaho cases in kinetics.py, unsuccessful so far

### CODE REVIEW

**Comment by erjank** [comment]
Cool.

Before we can merge in this pull request, a couple housekeeping steps:

1. git pull class master # You'll have some merge conflicts to manage.
2. git rm idaho_infections.csv # Only need one of these now that you've made a directory for data.

**Comment by ashtonenrriques** [comment]
Is there a way to add just the contributors.txt and new directory without
kinetics.py? My kinetics.py is not ready since I'm still working on the
graphing of actual data. I believe I fixed the merge conflict with
contributors.txt

Ashton Enrriques

**Comment by jennyfothergill** [comment]
@ashtonenrriques yes we could--it would involve making a branch! [https://www.atlassian.com/git/tutorials/using-branches](https://www.atlassian.com/git/tutorials/using-branches) We can go over this during an office hour if you like. :)

**Comment by erjank** [comment]
Hi Ashton!
Committing your current changes (they don't have to work!) and then doing a `git pull class master`  (resolving any conflicts), then a `git push` will let us merge this.

**Review by jennyfothergill — CHANGES_REQUESTED** [review]
see comments

**Comment by ashtonenrriques** [comment]
Will it work now?

**Pull request merged**
