### PR TITLE
I deleted the contributors bc it was a copy

### PR DESCRIPTION
**Pull request by hayesneukom**

### CODE REVIEW

**Comment by jennyfothergill** [comment]
@hayesneukom let's make sure to add the names from contributors to contributors.txt before we delete it

**Review by jennyfothergill — CHANGES_REQUESTED** [review]
please add the names from contributors to contributors.txt before we delete it

**Comment by hayesneukom** [comment]
Someone took care of this already

**Comment by jennyfothergill** [comment]
@erjank is fixing this one so I'll close it

**Pull request closed without merging**
