### PR TITLE
Contrubutors.txt Edit

### PR DESCRIPTION
**Pull request by CodyLacoursiere**
Put my name on contributors.txt

### CODE REVIEW

**Comment by jennyfothergill** [comment]
@CodyLacoursiere are you sure you want to change the labels on kinetics.py back to chemical kinetics?

**Comment by CodyLacoursiere** [comment]
@jennyfothergill No lol I deleted the head so it saved only the part that I had preciously!

**Comment by CodyLacoursiere** [comment]
I didn't mean to close it!!!

**Comment by jennyfothergill** [comment]
No worries, you can change this pull request through the github website, or through the terminal by pushing your changes to your fork.

**Comment by jennyfothergill** [comment]
Cool! it looks like you fixed it :)

**Review by jennyfothergill — APPROVED** [review]

**Pull request merged**
