### PR TITLE
Edited README

### PR DESCRIPTION
**Pull request by carmenwu1**

### CODE REVIEW

**Review by jennyfothergill — CHANGES_REQUESTED** [review]
Let's add the names from contributors before we delete it!

**Comment by carmenwu1** [comment]
Okay, it should be fixed now. I just combined the contributor files together and made sure there were no duplicates

**Review by jennyfothergill — CHANGES_REQUESTED** [review]
Once I merge @erjank's PR fixing the duplicate files, let's have you do a git pull class master, then this PR will be ready to merge

**Comment by carmenwu1** [comment]
Just fixed my contributors so let's hope that fixes everything.

**Comment by jennyfothergill** [comment]
I'm reopening this because your other changes are good! just do git pull class master, fix the merge conflicts (vim, fix, add, commit), and then git push!

**Comment by carmenwu1** [comment]
No more branch conflicts!!!

**Comment by jennyfothergill** [comment]
Nice! do git push and then those changes will show up here C:

**Comment by carmenwu1** [comment]
Just pushed it.

**Review by jennyfothergill — APPROVED** [review]

**Pull request merged**
