### PR TITLE
Pull request test

### PR DESCRIPTION
**Pull request by sampiraino**
Nothing really to add

### CODE REVIEW

**Comment by jennyfothergill** [comment]
@sampiraino, your change to kinetics.py will not run in python (line 20). Please fix before I can merge.

**Comment by sampiraino** [comment]
Okay, I believe I was able to return to original

**Comment by jennyfothergill** [comment]
I like it! I just commented on your issue before looking at this, so I'm happy to see you figured out pandas on your own! Let's rename finding to finding.py to let people know that it's a python script and add the source for the data to the readme, otherwise this looks great!
You can add a link in markdown like this `[link text](url)`
You can tell git to rename a file like this `git mv oldfilename newfilename`

**Comment by sampiraino** [comment]
Okay, I've updated changes. I link just added the link hashtagged in the links section of README

**Pull request merged**
